source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.3'

gem 'bcrypt', '3.1.18'
gem 'bootsnap', require: false
gem 'jwt', '2.8.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'
gem 'sqlite3', '~> 1.4'
gem 'rack-cors', '2.0.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', '1.9.2', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '6.4.3'
  gem 'faker', '2.21.0'
  gem 'rspec-rails', '6.1.2'
  gem 'shoulda-matchers', '6.2.0'
end

group :development do
  gem 'htmlbeautifier', '1.4.3'
  gem 'solargraph', '0.50.0'
  gem 'web-console', '4.2.1'
end
